# This is a basic workflow to help you get started with Actions

name: HyperShift CI Downstream

# Controls when the workflow will run
on:
  schedule:
    # Runs "8:00AM each day" (see https://crontab.guru)
    - cron: '30 11 * * 1,2,3,4,5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v3
    - name: Query build in Quay.io
      id: quay
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://quay.io/api/v1/repository/acm-d/acm-custom-registry/tag/?limit=50'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json"}'
    - name: Push build ID to Git
      run: |
        snapshot=$(echo ${{ toJson(steps.quay.outputs.response) }} | jq '[ .tags[].name] | map(select(. | startswith("2.8.0-DOWNSTREAM")))' | jq .[0] | tr -d '"')
        echo $snapshot > snapshot.txt
        cat snapshot.txt
        git config --global user.email "phwu@redhat.com"
        git config --global user.name "ACM HyperShift CI Bot"
        git add snapshot.txt
        git commit -m $snapshot
        git push origin main
